// Generated by CoffeeScript 1.7.1

/* 
author phuc
email phuccntt1990@gmail.com
 */

(function() {
  var fileCss, fileJs;

  fileJs = ['js/**/*.js'];

  fileCss = ['css/**/*.css'];

  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      'sails-linker': {
        devJs: {
          options: {
            startTag: '<!--SCRIPTS-->',
            endTag: '<!--SCRIPTS END-->',
            fileTmpl: '<script src="%"></script>',
            appRoot: 'app/'
          },
          files: {
            'index.html': [fileJs]
          }
        },
        devCss: {
          options: {
            startTag: '<!--STYLE-->',
            endTag: '<!--STYLE END-->',
            fileTmpl: '<link rel="stylesheet" href="%s">',
            appRoot: 'app'
          },
          files: {
            'index.html': [fileCss]
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-sails-linker');
    grunt.registerTask('test', ['sails-linker']);
  };

}).call(this);
